"""asmodean: few-body scattering experiments in an analytical potential.

Integrates up to 10 softened bodies of arbitrary masses in a static analytical
potential generated by lanfear (an SCF, disc-basis or multi-species
composite potential, never rotating), with Gadget spline softening between the
bodies, optional Chandrasekhar dynamical friction, momentum-conserving mergers
of bodies that come within a collision distance, and removal of ejected bodies.
The C++ core does the integration; this package builds the experiments and
analyses the results.

Typical use::

    import lanfear as lf
    import asmodean as am

    ps = lf.ParticleSystem.from_gadget_hdf5("snap.hdf5")
    ps.prepare(pattern_speed="none")          # the figure never rotates
    pot = am.ExternalPotential.from_lanfear(
        lf.Potential.from_particles(ps, n_max=12, l_max=4),
        include_black_holes=False,            # the BHs are the bodies instead
    )

    bodies = am.BodySystem()
    bodies.add_binary([0.01, 0.01], semimajor_axis=0.01, eccentricity=0.5,
                      softening=1e-4, labels=["BH1", "BH2"])
    bodies.add_incoming_body(0.01, v_infinity=50.0, impact_parameter=0.005,
                             distance=0.2, softening=1e-4, label="BH3")

    friction = am.DynamicalFriction.from_potential(pot, r_min=1e-3, r_max=50.0)
    result = am.integrate(
        bodies, pot, friction=friction, n_periods=500, period="binary",
        collision_distance=1e-4, ejection_radius=0.1,
    )
    print(result.summary())
    print(am.classify_outcome(result).describe(result.labels))
    result.save("result.npz")
"""

from ._logging import configure as _configure, get_logger, set_verbosity
from ._package_info import print_package_info
from . import _core
from .units import DEFAULT_G, UnitSystem
from .potential import ExternalPotential
from .bodies import MAX_BODIES, BodySystem, kepler_to_cartesian, rotation_matrix
from .friction import DynamicalFriction
from .results import (
    BODY_STATUSES,
    EVENT_TYPES,
    STOP_REASONS,
    Event,
    ScatteringResult,
)
from .analysis import (
    BoundPair,
    OrbitalElements,
    Outcome,
    bound_pairs,
    bound_pairs_from_state,
    classify_outcome,
    hard_binary_semimajor_axis,
    orbital_elements,
    pair_elements,
)
from .scattering import (
    IntegrationSettings,
    ScatteringSetup,
    estimate_period,
    integrate,
    integrate_ensemble,
)

# Set up the package logger as soon as asmodean is imported (default WARNING).
# Control it from a calling script with asmodean.set_verbosity("INFO").
_configure()

__all__ = [
    "DEFAULT_G",
    "UnitSystem",
    "ExternalPotential",
    "MAX_BODIES",
    "BodySystem",
    "kepler_to_cartesian",
    "rotation_matrix",
    "DynamicalFriction",
    "Event",
    "ScatteringResult",
    "STOP_REASONS",
    "EVENT_TYPES",
    "BODY_STATUSES",
    "OrbitalElements",
    "BoundPair",
    "Outcome",
    "orbital_elements",
    "bound_pairs",
    "bound_pairs_from_state",
    "pair_elements",
    "classify_outcome",
    "hard_binary_semimajor_axis",
    "IntegrationSettings",
    "ScatteringSetup",
    "estimate_period",
    "integrate",
    "integrate_ensemble",
    "set_verbosity",
    "get_logger",
    "print_package_info",
    "_core",
]

__version__ = "0.1.0"
