"""The static analytical background potential, taken from lanfear.

asmodean does not fit potentials itself: it takes one generated by lanfear -- a
:class:`lanfear.Potential` (Hernquist-Ostriker SCF), a
:class:`lanfear.DiscPotential` (Miyamoto-Nagai basis) or a
:class:`lanfear.MultiComponentPotential` (a per-species superposition), with
any softened black holes attached -- and rebuilds it inside asmodean's own C++
core from the state lanfear pickles its C++ potential with. lanfear's C++ is
header-only and compiled into asmodean, so the forces are exactly those lanfear
evaluates, with no python in the integration loop.

The figure never rotates: a pattern speed carried by the lanfear potential is
ignored (with a warning), and the potential is static in the inertial frame.

The core works in the potential's internal units (``G = 1``, length unit = the
potential's scale radius, mass unit = its field mass; see
:class:`~asmodean.UnitSystem`). The methods here take and return physical units.
"""

from __future__ import annotations

from typing import Optional

import numpy as np

from . import _core
from ._logging import get_logger
from .units import DEFAULT_G, UnitSystem

logger = get_logger(__name__)

_POTENTIAL_FORMAT = "asmodean-potential-1"


def _black_hole_array(black_holes, include: bool) -> np.ndarray:
    """(k, 5) array of lanfear black-hole tuples ``(mass, x, y, z, softening)``.

    Parameters
    ----------
    black_holes : sequence of tuple
        The black holes from a lanfear core's pickled state.
    include : bool
        If False, return an empty (0, 5) array.

    Returns
    -------
    black_holes : numpy.ndarray
        (k, 5) array in the potential's internal units.
    """
    if not include or len(black_holes) == 0:
        return np.zeros((0, 5))
    return np.asarray([list(bh) for bh in black_holes], dtype=np.float64).reshape(-1, 5)


def _spec_from_lanfear_core(core, include_black_holes: bool = True) -> dict:
    """Describe a lanfear C++ potential as a asmodean spec dict.

    Parameters
    ----------
    core : lanfear._core.SCFPotential, DiscPotential or CompositePotential
        The lanfear C++ potential (e.g. ``potential.core``).
    include_black_holes : bool, optional
        Keep the softened black holes attached to the potential.

    Returns
    -------
    spec : dict
        The spec understood by ``asmodean._core.ExternalPotential``.

    Raises
    ------
    TypeError
        If ``core`` is not a recognised lanfear potential.
    """
    name = type(core).__name__
    if not hasattr(core, "__getstate__") or name not in (
        "SCFPotential",
        "DiscPotential",
        "CompositePotential",
    ):
        raise TypeError(
            f"expected a lanfear SCFPotential, DiscPotential or CompositePotential, "
            f"got {name}"
        )
    state = core.__getstate__()
    if name == "SCFPotential":
        n_max, l_max, s_cos, s_sin, bhs = state
        return {
            "kind": "scf",
            "n_max": int(n_max),
            "l_max": int(l_max),
            "coefficients_cos": np.asarray(s_cos, dtype=np.float64),
            "coefficients_sin": np.asarray(s_sin, dtype=np.float64),
            "black_holes": _black_hole_array(bhs, include_black_holes),
        }
    if name == "DiscPotential":
        a, b, coefficients, bhs = state
        return {
            "kind": "disc",
            "a": np.asarray(a, dtype=np.float64),
            "b": np.asarray(b, dtype=np.float64),
            "coefficients": np.asarray(coefficients, dtype=np.float64),
            "black_holes": _black_hole_array(bhs, include_black_holes),
        }
    components, bhs = state
    return {
        "kind": "composite",
        "components": [
            {
                "potential": _spec_from_lanfear_core(sub, include_black_holes),
                "coord_scale": float(coord_scale),
                "phi_weight": float(phi_weight),
                "acc_weight": float(acc_weight),
                "label": str(label),
            }
            for sub, coord_scale, phi_weight, acc_weight, label in components
        ],
        "black_holes": _black_hole_array(bhs, include_black_holes),
    }


def _spec_to_arrays(spec: dict, prefix: str) -> dict:
    """Flatten a (possibly nested) spec into ``.npz``-storable arrays.

    Parameters
    ----------
    spec : dict
        A potential spec.
    prefix : str
        Key prefix (nested components extend it).

    Returns
    -------
    arrays : dict of str to numpy.ndarray
        The flattened spec.
    """
    out = {}
    for key, value in spec.items():
        if key == "components":
            out[f"{prefix}n_components"] = np.asarray(len(value), dtype=np.int64)
            for k, comp in enumerate(value):
                cp = f"{prefix}component{k}/"
                out.update(_spec_to_arrays(comp["potential"], f"{cp}potential/"))
                for field in ("coord_scale", "phi_weight", "acc_weight", "label"):
                    out[f"{cp}{field}"] = np.asarray(comp[field])
        else:
            out[f"{prefix}{key}"] = np.asarray(value)
    return out


def _spec_from_arrays(arrays, prefix: str) -> dict:
    """Inverse of :func:`_spec_to_arrays`.

    Parameters
    ----------
    arrays : mapping of str to numpy.ndarray
        The stored arrays.
    prefix : str
        Key prefix used when storing.

    Returns
    -------
    spec : dict
        The reconstructed spec.
    """
    kind = str(arrays[f"{prefix}kind"])
    spec: dict = {"kind": kind}
    if kind == "none":
        return spec
    spec["black_holes"] = np.asarray(arrays[f"{prefix}black_holes"]).reshape(-1, 5)
    if kind == "scf":
        spec["n_max"] = int(arrays[f"{prefix}n_max"])
        spec["l_max"] = int(arrays[f"{prefix}l_max"])
        spec["coefficients_cos"] = np.asarray(arrays[f"{prefix}coefficients_cos"])
        spec["coefficients_sin"] = np.asarray(arrays[f"{prefix}coefficients_sin"])
    elif kind == "disc":
        for key in ("a", "b", "coefficients"):
            spec[key] = np.asarray(arrays[f"{prefix}{key}"])
    elif kind == "composite":
        n = int(arrays[f"{prefix}n_components"])
        spec["components"] = []
        for k in range(n):
            cp = f"{prefix}component{k}/"
            spec["components"].append(
                {
                    "potential": _spec_from_arrays(arrays, f"{cp}potential/"),
                    "coord_scale": float(arrays[f"{cp}coord_scale"]),
                    "phi_weight": float(arrays[f"{cp}phi_weight"]),
                    "acc_weight": float(arrays[f"{cp}acc_weight"]),
                    "label": str(arrays[f"{cp}label"]),
                }
            )
    else:
        raise ValueError(f"unknown potential kind '{kind}'")
    return spec


def fibonacci_directions(n: int) -> np.ndarray:
    """Near-uniform unit vectors on the sphere (Fibonacci lattice).

    Parameters
    ----------
    n : int
        Number of directions.

    Returns
    -------
    directions : numpy.ndarray
        (n, 3) unit vectors.
    """
    k = np.arange(n) + 0.5
    cos_theta = 1.0 - 2.0 * k / n
    sin_theta = np.sqrt(1.0 - cos_theta**2)
    phi = np.pi * (1.0 + np.sqrt(5.0)) * k
    return np.stack(
        [sin_theta * np.cos(phi), sin_theta * np.sin(phi), cos_theta], axis=1
    )


class ExternalPotential:
    """A static analytical potential for the bodies to move in.

    Build with :meth:`from_lanfear` (the usual route), :meth:`from_lanfear_core`
    (a bare lanfear C++ potential plus its units) or :meth:`none` (no background
    potential: a pure few-body problem).

    Parameters
    ----------
    spec : dict
        Description of the potential understood by the C++ core (see
        :meth:`from_lanfear`); ``{"kind": "none"}`` for no potential.
    units : UnitSystem
        The potential's internal unit system (its scale radius, field mass and
        G).
    """

    def __init__(self, spec: dict, units: UnitSystem) -> None:
        self._spec = spec
        self.units = units
        self._core = _core.ExternalPotential(spec)

    # ------------------------------------------------------------- builders
    @classmethod
    def from_lanfear(
        cls, potential, include_black_holes: bool = True
    ) -> "ExternalPotential":
        """Take a potential built by lanfear.

        Parameters
        ----------
        potential : lanfear.Potential, lanfear.DiscPotential or lanfear.MultiComponentPotential
            The lanfear potential. Its ``core``, ``scale_radius``,
            ``field_mass`` and ``G`` define the potential and its units. Any
            pattern speed is ignored: the figure never rotates here.
        include_black_holes : bool, optional
            Keep the softened black holes lanfear attached to the potential
            (default True). Set False when the black holes are integrated as
            bodies instead (see :meth:`asmodean.BodySystem.from_particles`), so
            they are not counted twice.

        Returns
        -------
        potential : ExternalPotential
            The potential, ready for :func:`asmodean.integrate`.
        """
        omega = getattr(potential, "pattern_speed", None)
        if omega is not None and np.any(np.asarray(omega) != 0.0):
            logger.warning(
                f"Ignoring the lanfear potential's pattern speed "
                f"{np.round(np.asarray(omega), 4)}: asmodean integrates in a static "
                f"(non-rotating) potential"
            )
        return cls.from_lanfear_core(
            potential.core,
            scale_radius=potential.scale_radius,
            field_mass=potential.field_mass,
            G=potential.G,
            include_black_holes=include_black_holes,
        )

    @classmethod
    def from_lanfear_core(
        cls,
        core,
        scale_radius: float,
        field_mass: float,
        G: float = DEFAULT_G,
        include_black_holes: bool = True,
    ) -> "ExternalPotential":
        """Take a bare lanfear C++ potential, with its unit system.

        Parameters
        ----------
        core : lanfear._core.SCFPotential, DiscPotential or CompositePotential
            The lanfear C++ potential, in its own internal (HO) units.
        scale_radius : float
            Physical length of the potential's internal length unit.
        field_mass : float
            Physical mass of the potential's internal mass unit.
        G : float, optional
            Gravitational constant in the physical unit system (default Gadget).
        include_black_holes : bool, optional
            Keep the softened black holes attached to the potential.

        Returns
        -------
        potential : ExternalPotential
            The potential.
        """
        spec = _spec_from_lanfear_core(core, include_black_holes)
        pot = cls(spec, UnitSystem(length=scale_radius, mass=field_mass, G=G))
        logger.info(
            f"Using lanfear {type(core).__name__} as the external potential "
            f"({pot.n_black_holes} attached black hole(s)); length unit "
            f"{scale_radius:.4g}, mass unit {field_mass:.4g}"
        )
        return pot

    @classmethod
    def none(cls, units: Optional[UnitSystem] = None) -> "ExternalPotential":
        """No background potential: the bodies interact only with each other.

        Parameters
        ----------
        units : UnitSystem, optional
            Internal unit system to integrate in. Defaults to length 1, mass 1
            and the Gadget G; :func:`asmodean.integrate` instead picks units
            matched to the bodies when no potential is given at all.

        Returns
        -------
        potential : ExternalPotential
            The null potential.
        """
        return cls({"kind": "none"}, units or UnitSystem(length=1.0, mass=1.0))

    # ----------------------------------------------------------- properties
    @property
    def core(self):
        """The C++ potential used by the integrator.

        Returns
        -------
        core : asmodean._core.ExternalPotential
            The wrapped C++ object.
        """
        return self._core

    @property
    def spec(self) -> dict:
        """The spec dict the C++ potential was built from.

        Returns
        -------
        spec : dict
            The potential description.
        """
        return self._spec

    @property
    def kind(self) -> str:
        """The potential type: ``"none"``, ``"scf"``, ``"disc"`` or ``"composite"``.

        Returns
        -------
        kind : str
            The potential type.
        """
        return self._core.kind

    @property
    def is_null(self) -> bool:
        """Whether there is no background potential.

        Returns
        -------
        is_null : bool
            True for :meth:`none`.
        """
        return self._core.is_null

    @property
    def n_black_holes(self) -> int:
        """Number of softened black holes attached to the potential itself.

        Returns
        -------
        n : int
            Number of attached point masses.
        """
        return self._core.num_black_holes

    # ---------------------------------------------------------- evaluation
    def potential(self, points) -> np.ndarray:
        """Potential at physical points.

        Parameters
        ----------
        points : array-like of float
            (N, 3) (or (3,)) positions in physical length units.

        Returns
        -------
        phi : numpy.ndarray
            (N,) potential in physical specific-energy units (velocity^2).
        """
        pts = np.atleast_2d(np.asarray(points, dtype=np.float64)) / self.units.length
        return self._core.potential_batch(pts) * self.units.specific_energy

    def acceleration(self, points) -> np.ndarray:
        """Acceleration at physical points.

        Parameters
        ----------
        points : array-like of float
            (N, 3) (or (3,)) positions in physical length units.

        Returns
        -------
        acc : numpy.ndarray
            (N, 3) acceleration in physical units (velocity^2 / length).
        """
        pts = np.atleast_2d(np.asarray(points, dtype=np.float64)) / self.units.length
        return self._core.acceleration_batch(pts) * self.units.acceleration

    def radial_acceleration(self, radius, n_directions: int = 128) -> np.ndarray:
        """Spherically averaged radial acceleration ``<a . r_hat>``.

        Parameters
        ----------
        radius : float or array-like of float
            Radii in physical length units.
        n_directions : int, optional
            Number of (Fibonacci-lattice) directions averaged over.

        Returns
        -------
        a_r : numpy.ndarray
            Radial acceleration at each radius (negative = inward), physical
            units.
        """
        r = np.atleast_1d(np.asarray(radius, dtype=np.float64))
        dirs = fibonacci_directions(n_directions)
        pts = (r[:, None, None] * dirs[None, :, :]).reshape(-1, 3)
        acc = self.acceleration(pts).reshape(len(r), n_directions, 3)
        return np.mean(np.sum(acc * dirs[None, :, :], axis=2), axis=1)

    def enclosed_mass(self, radius, n_directions: int = 128) -> np.ndarray:
        """Mass enclosed within a sphere, from Gauss's theorem.

        ``M(<r) = -r^2 <a_r> / G``, exact for the spherical average of any
        potential (including off-centre black holes).

        Parameters
        ----------
        radius : float or array-like of float
            Radii in physical length units.
        n_directions : int, optional
            Number of directions averaged over.

        Returns
        -------
        mass : numpy.ndarray
            Enclosed mass at each radius (physical units).
        """
        r = np.atleast_1d(np.asarray(radius, dtype=np.float64))
        return -(r**2) * self.radial_acceleration(r, n_directions) / self.units.G

    def circular_velocity(self, radius, n_directions: int = 128) -> np.ndarray:
        """Circular velocity of the spherically averaged potential.

        Parameters
        ----------
        radius : float or array-like of float
            Radii in physical length units.
        n_directions : int, optional
            Number of directions averaged over.

        Returns
        -------
        v_circ : numpy.ndarray
            ``sqrt(-r <a_r>)`` at each radius (physical units); zero where the
            averaged force is not inward.
        """
        r = np.atleast_1d(np.asarray(radius, dtype=np.float64))
        a_r = self.radial_acceleration(r, n_directions)
        return np.sqrt(np.clip(-r * a_r, 0.0, None))

    def circular_period(self, radius, n_directions: int = 128) -> np.ndarray:
        """Circular orbital period of the spherically averaged potential.

        Parameters
        ----------
        radius : float or array-like of float
            Radii in physical length units.
        n_directions : int, optional
            Number of directions averaged over.

        Returns
        -------
        period : numpy.ndarray
            ``2 pi r / v_circ`` (physical time units); infinite where the
            circular velocity vanishes.
        """
        r = np.atleast_1d(np.asarray(radius, dtype=np.float64))
        v = self.circular_velocity(r, n_directions)
        with np.errstate(divide="ignore"):
            return np.where(v > 0, 2.0 * np.pi * r / np.where(v > 0, v, 1.0), np.inf)

    # ----------------------------------------------------------------- io
    def to_arrays(self, prefix: str = "potential/") -> dict:
        """Serialise to a dict of NumPy arrays (for ``.npz`` files).

        Parameters
        ----------
        prefix : str, optional
            Prefix for every key.

        Returns
        -------
        arrays : dict of str to numpy.ndarray
            The spec and the unit system.
        """
        arrays = {f"{prefix}_format": np.asarray(_POTENTIAL_FORMAT)}
        arrays.update(_spec_to_arrays(self._spec, f"{prefix}spec/"))
        arrays.update(self.units.to_arrays(f"{prefix}units/"))
        return arrays

    @classmethod
    def from_arrays(cls, arrays, prefix: str = "potential/") -> "ExternalPotential":
        """Rebuild from :meth:`to_arrays` output.

        Parameters
        ----------
        arrays : mapping of str to numpy.ndarray
            The stored arrays (e.g. an open ``.npz`` file).
        prefix : str, optional
            Prefix used when storing.

        Returns
        -------
        potential : ExternalPotential
            The reconstructed potential.

        Raises
        ------
        ValueError
            If the arrays do not hold a asmodean potential.
        """
        key = f"{prefix}_format"
        if key not in arrays or str(arrays[key]) != _POTENTIAL_FORMAT:
            raise ValueError("arrays do not hold a asmodean ExternalPotential")
        return cls(
            _spec_from_arrays(arrays, f"{prefix}spec/"),
            UnitSystem.from_arrays(arrays, f"{prefix}units/"),
        )

    def save(self, path) -> str:
        """Write the potential to a ``.npz`` file.

        Parameters
        ----------
        path : str or os.PathLike
            Destination file (``.npz`` is appended by NumPy if absent).

        Returns
        -------
        path : str
            The path written.
        """
        import os

        np.savez(path, **self.to_arrays())
        out = os.fspath(path)
        return out if out.endswith(".npz") else out + ".npz"

    @classmethod
    def load(cls, path) -> "ExternalPotential":
        """Read a potential written by :meth:`save`.

        Parameters
        ----------
        path : str or os.PathLike
            A ``.npz`` file written by :meth:`save`.

        Returns
        -------
        potential : ExternalPotential
            The reconstructed potential.
        """
        with np.load(path, allow_pickle=False) as npz:
            return cls.from_arrays(npz)

    def __getstate__(self):
        """Pickle support (the C++ object is rebuilt from the spec).

        Returns
        -------
        state : tuple
            ``(spec, units)``.
        """
        return (self._spec, self.units)

    def __setstate__(self, state) -> None:
        """Rebuild after unpickling.

        Parameters
        ----------
        state : tuple
            ``(spec, units)`` from :meth:`__getstate__`.
        """
        self.__init__(*state)

    def __repr__(self) -> str:
        """Short description.

        Returns
        -------
        text : str
            The representation.
        """
        return (
            f"ExternalPotential(kind='{self.kind}', n_black_holes={self.n_black_holes}, "
            f"units={self.units})"
        )
